---
title: My first git repo
author: David Benkeser
output: github_document
---

# My first commit

Here is some text that constitutes my first commit in my first repo.
I am now adding a new line to this first commit section of the readme.

# My second commit

Here is more text that will be added in my second commit.

# My third commit

Here is some final text for my third commit.

# My test branch

Here is some text that I will commit to the test branch.

# My new_test branch

Here is some text that I will commit to the new_-test branch.

# Contribution from resekneb

Hey benkeser, here is some great new code. And I've included an R chunk below!

```{r}
print("hello from R")
Sys.Date()
```

# Another BIG contribution from resekneb

Call me Ishmael. Some years ago -- never mind how long precisely -- having little or no money
in my purse and nothing particular to interest me on short, I thought I would sail about a little
and see the watery part of the world.

# A direct contribution from resekneb

Here's a contribution that I can push directly to Github.

